name       : font-firacode
version    : '1.204'
release    : 2
source     :
    - https://github.com/tonsky/FiraCode/releases/download/1.204/FiraCode_1.204.zip : 28ccc003173cec9de7857f8743b805d6b51eb68fb8be5e21ce2f8e1584f0939f
license    : OFL-1.1
component  : desktop.font
summary    : Fira Code is a monospaced font with programming ligatures
description: |
    Fira Code is a monospaced font with programming ligatures
patterns   :
    - otf: /usr/share/fonts/opentype
    - ttf: /usr/share/fonts/truetype
install    : |
    install -dm00644 $installdir/usr/share/fonts/{open,true}type/firacode/
    cp -R $workdir/otf/*.otf $installdir/usr/share/fonts/opentype/firacode/
    cp -R $workdir/ttf/*.ttf $installdir/usr/share/fonts/truetype/firacode/
