name       : font-firacode
version    : '4'
release    : 8
source     :
    - https://github.com/tonsky/FiraCode/releases/download/4/Fira_Code_v4.zip : 46ed45d1a793a56e13d31ed10fb7e09f5277731953a0d9522915644fc59086d8
license    : OFL-1.1
component  : desktop.font
summary    : Monospaced font with programming ligatures
description: |
    Fira Code is a monospaced font with programming ligatures.
patterns   :
    - otf : /usr/share/fonts/opentype
    - ttf : /usr/share/fonts/truetype
install    : |
    install -Dm00644 otf/*.otf -t $installdir/usr/share/fonts/opentype/firacode/
    install -Dm00644 ttf/*.ttf -t $installdir/usr/share/fonts/truetype/firacode/
