name       : font-firacode
version    : '1.207'
release    : 5
source     :
    - https://github.com/tonsky/FiraCode/archive/1.207.tar.gz : 4010f308578086d45226b30d3b2e11f40185fddf0d59611647b5f5cf684a5fab
license    : OFL-1.1
component  : desktop.font
summary    : Fira Code is a monospaced font with programming ligatures
description: |
    Fira Code is a monospaced font with programming ligatures
patterns   :
    - otf : /usr/share/fonts/opentype
    - ttf : /usr/share/fonts/truetype
install    : |
    install -Dm00644 distr/otf/*.otf -t $installdir/usr/share/fonts/opentype/firacode/
    install -Dm00644 distr/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/firacode/
