name       : font-firacode-otf
version    : 1.102
release    : 1
source     :
    - https://github.com/tonsky/FiraCode/releases/download/1.102/FiraCode_1.102.zip : fe3dc4af0c7e44d715b6f9a1bfc1adb5fee76a533016c0a2b0c3b3da8efb996d
license    : OFL-1.1
summary    : Fira Code is a monospaced font with programming ligatures
description: |
    Fira Code is a monospaced font with programming ligatures
install    : |
    fontDir=$installdir/usr/share/fonts/firacode
    install -dm644 $fontDir
    cp -R $srcdir/*.otf $fontDir/
