name       : font-firacode
version    : '3'
release    : 7
source     :
    - https://github.com/tonsky/FiraCode/releases/download/3/FiraCode_3.zip : 043fa00e002704aec6f8b5e1908faf099f9477160d00ad0260a8103329c3981b
license    : OFL-1.1
component  : desktop.font
summary    : Monospaced font with programming ligatures
description: |
    Fira Code is a monospaced font with programming ligatures.
patterns   :
    - otf : /usr/share/fonts/opentype
    - ttf : /usr/share/fonts/truetype
install    : |
    install -Dm00644 otf/*.otf -t $installdir/usr/share/fonts/opentype/firacode/
    install -Dm00644 ttf/*.ttf -t $installdir/usr/share/fonts/truetype/firacode/
