name       : font-firacode
version    : '1.206'
release    : 4
source     :
    - https://github.com/tonsky/FiraCode/archive/1.206.tar.gz : f5f55ca004c2a1b685d0daf60a56672c2a9891e241f77b351a63670968e02940
license    : OFL-1.1
component  : desktop.font
summary    : Fira Code is a monospaced font with programming ligatures
description: |
    Fira Code is a monospaced font with programming ligatures
patterns   :
    - otf : /usr/share/fonts/opentype
    - ttf : /usr/share/fonts/truetype
install    : |
    install -dm00644 $installdir/usr/share/fonts/{open,true}type/firacode/
    cp -R $workdir/distr/otf/*.otf $installdir/usr/share/fonts/opentype/firacode/
    cp -R $workdir/distr/ttf/*.ttf $installdir/usr/share/fonts/truetype/firacode/
