name       : font-firacode
version    : '2'
release    : 6
source     :
    - https://github.com/tonsky/FiraCode/archive/2.tar.gz : 6ab6e193f01d50511f31822486216e1b6ba28eb41624aa2120b267e9ca20bf00
license    : OFL-1.1
component  : desktop.font
summary    : Fira Code is a monospaced font with programming ligatures
description: |
    Fira Code is a monospaced font with programming ligatures
patterns   :
    - otf : /usr/share/fonts/opentype
    - ttf : /usr/share/fonts/truetype
install    : |
    install -Dm00644 distr/otf/*.otf -t $installdir/usr/share/fonts/opentype/firacode/
    install -Dm00644 distr/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/firacode/
