name       : font-firacode
version    : '5.2'
release    : 9
source     :
    - https://github.com/tonsky/FiraCode/releases/download/5.2/Fira_Code_v5.2.zip : 521a72be00dd22678d248e63f817c0c79c1b6f23a4fbd377eba73d30cdca5efd
license    : OFL-1.1
component  : desktop.font
summary    : Monospaced font with programming ligatures
description: |
    Fira Code is a monospaced font with programming ligatures.
replaces   :
    - ttf : font-firacode-otf
patterns   :
    - ttf : /usr/share/fonts/truetype
install    : |
    install -Dm00644 ttf/*.ttf -t $installdir/usr/share/fonts/truetype/firacode/
