name       : font-firacode
version    : '6.2'
release    : 10
source     :
    - https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip : 0949915ba8eb24d89fd93d10a7ff623f42830d7c5ffc3ecbf960e4ecad3e3e79
homepage   : https://github.com/tonsky/FiraCode
license    : OFL-1.1
component  :
    - desktop.font
    - ttf : desktop.font
summary    : Monospaced font with programming ligatures
description: |
    Fira Code is a monospaced font with programming ligatures.
replaces   :
    - ttf : font-firacode-otf
patterns   :
    - ttf : /usr/share/fonts/truetype
install    : |
    install -Dm00644 ttf/*.ttf -t $installdir/usr/share/fonts/truetype/firacode/
