name       : font-firacode
version    : '1.205'
release    : 3
source     :
    - https://github.com/tonsky/FiraCode/archive/1.205.tar.gz : e00dd9f6076dd3a525135e79e48544723797daaaf7b15e4199637d804e50a468
license    : OFL-1.1
component  : desktop.font
summary    : Fira Code is a monospaced font with programming ligatures
description: |
    Fira Code is a monospaced font with programming ligatures
patterns   :
    - otf : /usr/share/fonts/opentype
    - ttf : /usr/share/fonts/truetype
install    : |
    install -dm00644 $installdir/usr/share/fonts/{open,true}type/firacode/
    cp -R $workdir/distr/otf/*.otf $installdir/usr/share/fonts/opentype/firacode/
    cp -R $workdir/distr/ttf/*.ttf $installdir/usr/share/fonts/truetype/firacode/
